# Generated by Django 5.2.6 on 2025-09-23 13:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('nickname', models.CharField(blank=True, help_text='사용자 닉네임', max_length=50, null=True, unique=True)),
                ('email', models.EmailField(blank=True, help_text='이메일 주소', max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, help_text='전화번호 (국제 형식)', max_length=20, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, help_text='이름', max_length=50)),
                ('last_name', models.CharField(blank=True, help_text='성', max_length=50)),
                ('profile_image', models.URLField(blank=True, help_text='프로필 이미지 URL', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='계정 활성화 상태')),
                ('is_email_verified', models.BooleanField(default=False, help_text='이메일 인증 여부')),
                ('is_phone_verified', models.BooleanField(default=False, help_text='전화번호 인증 여부')),
                ('last_login', models.DateTimeField(blank=True, help_text='마지막 로그인 시간', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='계정 생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='계정 수정 시간')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_set', related_query_name='custom_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_set', related_query_name='custom_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자들',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('kakao', 'Kakao'), ('naver', 'Naver')], help_text='소셜 로그인 제공자', max_length=20)),
                ('provider_id', models.CharField(help_text='소셜 제공자의 사용자 ID', max_length=100)),
                ('provider_email', models.EmailField(blank=True, help_text='소셜에서 받은 이메일', max_length=254, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='소셜에서 받은 추가 정보')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='연동 생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='연동 수정 시간')),
                ('user', models.ForeignKey(help_text='연동된 사용자', on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='users.user')),
            ],
            options={
                'verbose_name': '소셜 계정',
                'verbose_name_plural': '소셜 계정들',
                'db_table': 'social_accounts',
                'indexes': [models.Index(fields=['user', 'provider'], name='social_acco_user_id_e2981d_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_id'), name='unique_social_account')],
            },
        ),
    ]
