# Generated by Django 5.2.6 on 2025-09-23 14:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(help_text='사용자 ID (외래키 제약 없이 참조)')),
                ('account_code', models.CharField(help_text='계정과목 코드 (예: 1100, 4100)', max_length=10)),
                ('account_name', models.CharField(help_text='계정과목명 (예: 현금, 식비)', max_length=50)),
                ('account_type', models.CharField(choices=[('asset', '자산'), ('liability', '부채'), ('equity', '자본'), ('revenue', '수익'), ('expense', '비용')], help_text='계정과목 유형', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='활성화 상태')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='생성 시간')),
                ('parent', models.ForeignKey(blank=True, help_text='상위 계정과목', null=True, on_delete=django.db.models.deletion.CASCADE, to='finances.account')),
            ],
            options={
                'verbose_name': '계정과목',
                'verbose_name_plural': '계정과목들',
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(help_text='사용자 ID (외래키 제약 없이 참조)')),
                ('entry_date', models.DateField(help_text='거래 일자')),
                ('description', models.CharField(blank=True, help_text='거래 설명', max_length=255)),
                ('reference_id', models.CharField(blank=True, help_text='참조 ID (AI 파싱 시 원본 데이터 참조용)', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='생성 시간')),
            ],
            options={
                'verbose_name': '분개',
                'verbose_name_plural': '분개들',
                'db_table': 'journal_entries',
                'indexes': [models.Index(fields=['user_id'], name='journal_ent_user_id_1d3de3_idx'), models.Index(fields=['entry_date'], name='journal_ent_entry_d_8a53f9_idx')],
            },
        ),
        migrations.CreateModel(
            name='TransactionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='차변 금액', max_digits=15)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='대변 금액', max_digits=15)),
                ('account', models.ForeignKey(help_text='계정과목', on_delete=django.db.models.deletion.CASCADE, to='finances.account')),
                ('journal_entry', models.ForeignKey(help_text='분개', on_delete=django.db.models.deletion.CASCADE, related_name='transaction_details', to='finances.journalentry')),
            ],
            options={
                'verbose_name': '분개 상세',
                'verbose_name_plural': '분개 상세들',
                'db_table': 'transaction_details',
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['user_id'], name='accounts_user_id_6786b5_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['account_code'], name='accounts_account_e87462_idx'),
        ),
        migrations.AddIndex(
            model_name='transactiondetail',
            index=models.Index(fields=['journal_entry'], name='transaction_journal_4a8316_idx'),
        ),
        migrations.AddIndex(
            model_name='transactiondetail',
            index=models.Index(fields=['account'], name='transaction_account_303d33_idx'),
        ),
    ]
