# Generated by Django 5.2.6 on 2025-09-23 14:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(help_text='사용자 ID (외래키 제약 없이 참조)')),
                ('name', models.CharField(help_text='카테고리 이름', max_length=50)),
                ('color', models.CharField(blank=True, help_text='색상 코드 (hex)', max_length=7)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='생성 시간')),
            ],
            options={
                'verbose_name': '일정 카테고리',
                'verbose_name_plural': '일정 카테고리들',
                'db_table': 'schedule_categories',
                'indexes': [models.Index(fields=['user_id'], name='schedule_ca_user_id_3ddcca_idx')],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(help_text='사용자 ID (외래키 제약 없이 참조)')),
                ('title', models.CharField(help_text='일정 제목', max_length=255)),
                ('description', models.TextField(blank=True, help_text='일정 설명')),
                ('start_datetime', models.DateTimeField(help_text='시작 일시')),
                ('end_datetime', models.DateTimeField(blank=True, help_text='종료 일시', null=True)),
                ('is_all_day', models.BooleanField(default=False, help_text='하루종일 일정 여부')),
                ('status', models.CharField(choices=[('scheduled', '예정'), ('completed', '완료'), ('cancelled', '취소')], default='scheduled', help_text='일정 상태', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 시간')),
                ('category', models.ForeignKey(blank=True, help_text='일정 카테고리', null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.schedulecategory')),
            ],
            options={
                'verbose_name': '일정',
                'verbose_name_plural': '일정들',
                'db_table': 'schedules',
                'indexes': [models.Index(fields=['user_id'], name='schedules_user_id_6bbfc9_idx'), models.Index(fields=['start_datetime'], name='schedules_start_d_478e01_idx'), models.Index(fields=['user_id', 'start_datetime'], name='schedules_user_id_894391_idx')],
            },
        ),
    ]
